charts/gateway updated documentation, added custom healthchecks, added custom configuration options

diff --git a/charts/gateway/templates/configmap.yaml b/charts/gateway/templates/configmap.yaml
--- a/charts/gateway/templates/configmap.yaml
+++ b/charts/gateway/templates/configmap.yaml
@@ -115,6 +115,7 @@ data:
         </l7:Mappings>
     </l7:Bundle>
 {{- end }}
+{{- if .Values.bootstrap }}
 {{- if .Values.bootstrap.script.enabled }}
   003-parse-custom-files: |-
     #!/bin/bash
@@ -122,19 +123,22 @@ data:
     BUNDLE_DIR="$BASE_CONFIG_DIR/bundle"
     CUSTOM_ASSERTIONS_DIR="$BASE_CONFIG_DIR/custom-assertions"
     MODULAR_ASSERTIONS_DIR="$BASE_CONFIG_DIR/modular-assertions"
-    CUSTOM_SCRIPTS_DIR="$BASE_CONFIG_DIR/scripts/custom"
-    CUSTOM_HEALTHCHECK_DIR="$BASE_CONFIG_DIR/scripts/healthcheck"
+    CUSTOM_SHELL_SCRIPTS_DIR="$BASE_CONFIG_DIR/scripts"
     BASE_TARGET_DIR="/opt/SecureSpan/Gateway"
     TARGET_BUNDLE_DIR="$BASE_TARGET_DIR/node/default/etc/bootstrap/bundle"
     TARGET_CUSTOM_ASSERTIONS_DIR="$BASE_TARGET_DIR/runtime/modules/lib"
     TARGET_MODULAR_ASSERTIONS_DIR="$BASE_TARGET_DIR/runtime/modules/assertions"
-    TARGET_CUSTOM_SCRIPTS_DIR="/opt/docker/rc.d"
-    TARGET_CUSTOM_HEALTHCHECK_DIR="/opt/docker/rc.d/diagnostic/health_check"
+    
+    error() {
+            # Send errors to stderr in case these get handled differently by the container PaaS on which this runs
+            echo "ERROR - ${1}" 1>&2
+            exit 1
+    }
 
     function cleanup() {
-      echo "***********************************************"
+      echo "***************************************************************************"
       echo "removing $BASE_CONFIG_DIR"
-      echo "***********************************************"
+      echo "***************************************************************************"
       rm -rf $BASE_CONFIG_DIR/*
     }
     
@@ -143,27 +147,44 @@ data:
         EXT=$2
         SOURCE_DIR=$3
         TARGET_DIR=$4
-        echo "***********************************************"
+        echo "***************************************************************************"
         echo "scanning for $TYPE in $SOURCE_DIR"
-        echo "***********************************************"
+        echo "***************************************************************************"
         FILES=$(find $3 -type f -name '*'$2 2>/dev/null)
         for file in $FILES; do
             name=$(basename "$file")
-            if [[ $EXT == ".sh" ]]; then
-                chmod +x $file
-            fi
             cp $file $4/$name
             echo -e "$name written to $4/$name"
+        done
+    }
+
+    function run() {
+        TYPE=$1
+        EXT=$2
+        SOURCE_DIR=$3
+        echo "***************************************************************************"
+        echo "scanning for $TYPE in $SOURCE_DIR"
+        echo "***************************************************************************"
+        FILES=$(find $3 -type f -name '*'$2 2>/dev/null)
+        for file in $FILES; do
+            name=$(basename "$file")
+            chmod +x $file
+            echo -e "running $name"
+            /bin/bash $file
+            if [ $? -ne 0 ]; then
+              echo "Failed executing the script: $file"
+              exit 1
+            fi
         done
     }
     
     copy "bundles" ".bundle" $BUNDLE_DIR $TARGET_BUNDLE_DIR
     copy "custom assertions" ".jar" $CUSTOM_ASSERTIONS_DIR $TARGET_CUSTOM_ASSERTIONS_DIR
     copy "modular assertions" ".aar" $MODULAR_ASSERTIONS_DIR $TARGET_MODULAR_ASSERTIONS_DIR
-    copy "custom scripts" ".sh" $CUSTOM_SCRIPTS_DIR $TARGET_CUSTOM_SCRIPTS_DIR
-    copy "custom healthcheck scripts" ".sh" $CUSTOM_HEALTHCHECK_DIR $TARGET_CUSTOM_HEALTHCHECK_DIR
+    run "custom shell scripts" ".sh" $CUSTOM_SHELL_SCRIPTS_DIR
 {{- if .Values.bootstrap.cleanup }}
     cleanup
+{{- end}}
 {{- end}}
     
 {{- end }}
